apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
  labels:
    name: auth-service
    app: authX
spec:
  type: NodePort
  ports:
    - port: 5000 # anyting tag to service used internally 
      targetPort: 5000 #image port
      nodePort: 31003 # outside
  selector:
    name: authapi-pod
    app: authX
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: default
  labels:
    app: authX
    name: auth-service
spec:
  template:
    metadata:
      name: authapi-pod
      labels:
        name: authapi-pod
        app: authX
    spec:
      imagePullSecrets:
        - name: regcred  #ecr auth secret
      containers:
        - name: authapi-pod
          image: 377379411010.dkr.ecr.ap-northeast-1.amazonaws.com/se:11 # {"$imagepolicy": "flux-system:identity"}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "200Mi" #megabytes
              cpu: "200m"   #.05 core
            limits:
              memory: "250Mi" #issues log file : OOM killed
              cpu: "250m"
          ports:
            - containerPort: 5000 #
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
          volumeMounts:
            - name: appsettings-volume
              mountPath: /app/appsettings.Development.json
              subPath: appsettings.Development.json
      volumes:
        - name: appsettings-volume
          secret:
            secretName: auth-secret
            # configMap:
            #     name: identity-configmap
  replicas: 1
  selector:
    matchLabels:
      app: authX 
