apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
    appsettings.Development.json: |-
      {
                  "Logging": {
            "LogLevel": {
              "Default": "Information",
              "Microsoft": "Warning",
              "Microsoft.Hosting.Lifetime": "Information"
            }
          },

          "IdentityUrl": "http://authserver:80",

          // Events in IDS4
          "Events": {
            "RaiseErrorEvents": true,
            "RaiseInformationEvents": true,
            "RaiseFailureEvents": true,
            "RaiseSuccessEvents": true
          },

          // Password options
          "PasswordOptions": {
            "RequiredLength": "7",
            "RequiredUniqueChars": "0",
            "RequireNonAlphanumeric": "0",
            "RequireLowercase": "0",
            "RequireUppercase": "0",
            "RequireDigit": "0",
            "RequireUniqueEmail": "0"
          },

          "SignInOptions": {
            "RequireConfirmedEmail": "1",
            "RequireConfirmedMobile": "1"
          },

          "DataProtectionTokenProviderOptions": {
            "TokenLifeSpanInHours": "2"
          },

          "EmailConfirmationTokenProviderOptions": {
            "TokenLifeSpanInHours": "72"
          },

          "LockoutIdenityOptions": {
            "MaxFailedAccessAttempts": "10",
            "DefaultLockoutTimeSpanInMinutes": "5"
          },

          "ServiceConfig": {
            "serviceDiscoveryAddress": "http://consul:8500",
            "serviceName": "austhserver",
            "serviceId": "austhserver001",
            "serviceAddress": "http://auth-service:80"
          },

          "UsedHostNames": [
            "http://localhost:8001"
          ],
          "ConnectionStrings": {
            "ApplicationDbContext": "Server=stockappdb.cyxqtem3lhop.ap-northeast-1.rds.amazonaws.com;Port=5432;Database=User;User Id=pgadmin;Password=Password;"
          },

          "Certificate": {
            "IsUsed": false,
            "Path": "<path to .pfx file>",
            "Password": "$CREDENTIAL_PLACEHOLDER$"
          }
      }
