apiVersion: v1
kind: Secret
metadata:
  name: Transaction-secret
type: Opaque
stringData:
    appsettings.Development.json: |-
      {
                  "Logging": {
            "LogLevel": {
              "Default": "Information",
              "Microsoft": "Warning",
              "Microsoft.Hosting.Lifetime": "Information",
              "Elastic.Apm": "Information"
            }
          },

          "LogFileName": "UserServiceLogs.txt",

          "IdentityUrl": "http://authserver:80",

          // Swtich on/off for admin user 2fa
          "IsAdmin2FA": "1",

          "IsCandidate2FA": "1",

          // Password options
          "PasswordOptions": {
            "RequiredLength": "7",
            "RequiredUniqueChars": "0",
            "RequireNonAlphanumeric": "0",
            "RequireLowercase": "0",
            "RequireUppercase": "0",
            "RequireDigit": "0",
            "RequireUniqueEmail": "0"
          },

          "SignInOptions": {
            "RequireConfirmedEmail": "1",
            "RequireConfirmedMobile": "1"
          },

          "DataProtectionTokenProviderOptions": {
            "TokenLifeSpanInHours": "2"
          },

          "EmailConfirmationTokenProviderOptions": {
            "TokenLifeSpanInHours": "72"
          },

          "LockoutIdenityOptions": {
            "MaxFailedAccessAttempts": "10",
            "DefaultLockoutTimeSpanInMinutes": "5"
          },

          "IdentityClientRegistration": {
            "TokenEndpoint": "http://auth-service:80/connect/token",
            "ClientId": "ro.client",
            "ClientSecret": "secret"
          },

          "UsedHostNames": [
            "http://localhost:4100",
            "http://localhost:4200"
          ],
          "ConnectionStrings": {
            "ApplicationDbContext": "Server=stockappdb.cyxqtem3lhop.ap-northeast-1.rds.amazonaws.com;Port=5432;Database=stockappdb;User Id=pgadmin;Password=Password;"
          }
      }
